Traceback (most recent call last):
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\site-packages\nbclient\client.py", line 1319, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\site-packages\nbclient\client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\site-packages\nbclient\client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "f:\ProgramFiles\condaEnvs\cds_env\lib\site-packages\nbclient\client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import netCDF4 as nc
from utils.compute_linegraph import compute_df_stats, plot_linegraph, plot_linegraph_with_slider

# Read netCDF file and variable data
filepath = r"./data/reanalysis-era5-land-monthly-means_2m_temperature_1950_2024.nc"
dataset = nc.Dataset(filepath, mode='r')
test_variable = 't2m'
variable_data = dataset[test_variable]

# Compute statistics
df_statistics = compute_df_stats(variable_data)

# Plot line graph for month=August (8)
plot_linegraph(selected_month=8, df_statistics=df_statistics)
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn[2], line 2[0m
[0;32m      1[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mnetCDF4[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mnc[39;00m
[1;32m----> 2[0m [38;5;28;01mfrom[39;00m[38;5;250m [39m[38;5;21;01mutils[39;00m[38;5;21;01m.[39;00m[38;5;21;01mcompute_linegraph[39;00m[38;5;250m [39m[38;5;28;01mimport[39;00m compute_df_stats, plot_linegraph, plot_linegraph_with_slider
[0;32m      4[0m [38;5;66;03m# Read netCDF file and variable data[39;00m
[0;32m      5[0m filepath [38;5;241m=[39m [38;5;124mr[39m[38;5;124m"[39m[38;5;124m./data/reanalysis-era5-land-monthly-means_2m_temperature_1950_2024.nc[39m[38;5;124m"[39m

File [1;32mH:\CoKLIMAx-II\source_en\notebooks\kurs4_vis_optionen\utils\compute_linegraph.py:7[0m
[0;32m      4[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mplt[39;00m
[0;32m      5[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mticker[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mticker[39;00m
[1;32m----> 7[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mplotly[39;00m[38;5;21;01m.[39;00m[38;5;21;01mgraph_objects[39;00m[38;5;250m [39m[38;5;28;01mas[39;00m[38;5;250m [39m[38;5;21;01mgo[39;00m
[0;32m      8[0m [38;5;28;01mimport[39;00m[38;5;250m [39m[38;5;21;01mcalendar[39;00m
[0;32m     10[0m [38;5;28;01mdef[39;00m[38;5;250m [39m[38;5;21mcompute_df_stats[39m(variable_data):
[0;32m     11[0m     [38;5;66;03m# Initialize lists to store statistics[39;00m

[1;31mModuleNotFoundError[0m: No module named 'plotly'

